services:
  hugo:
    image: klakegg/hugo:ext-alpine
    volumes:
      - .:/src
    working_dir: /src
    ports:
      - "1313:1313"
    command: server --bind=0.0.0.0 --disableFastRender

  cms-proxy:
    image: node:16-alpine
    restart: on-failure
    volumes:
      - .:/repo
    working_dir: /repo
    environment:
      - GIT_REPO_DIRECTORY=/repo       # point the proxy at your local Git checkout
      - PORT=8081                      # tell it what port to listen on
    command: >
      sh -c "npm install netlify-cms-proxy-server@^1.3.24 &&
             npx netlify-cms-proxy-server"
    ports:
      - "8081:8081"
